### ISSUE TITLE
Switch to a non-Bower version of the font-awesome assets?

### ISSUE THREAD

**Issue by acorncom** [martndemus/ember-font-awesome#108]
With the slow push to remove Bower from Ember, should we consider removing the Bower dependency for this add-on as well?

**Comment by josemarluedke** [comment]
Would be awesome to be able to remove the bower dependency from here. Even more now that emberjs/ember.js/pull/13022 has been merged.

**Comment by Panman8201** [comment]
Also posted this in the linked PR, but I can work on this. Question though, should the font awesome dep be in the addon or project? In that, should the project owner be able to change the imported version (then project)?

**Comment by buschtoens** [comment]
Closed by #118.

**Comment by Panman8201** [comment]
Thanks @buschtoens you beat me to it. :)
