### ISSUE TITLE
Assertion Failed: A helper named "fa-icon" could not be found when using with concat

### ISSUE THREAD

**Issue by olegantonyan** [martndemus/ember-font-awesome#111]
`{{concat 'Login ' (fa-icon 'sign-in')}}` gives me error:
`Assertion Failed: A helper named "fa-icon" could not be found`

But `{{fa-icon 'sign-in'}}` works.

**Comment by martndemus** [comment]
This is because `{{fa-icon}}` is a component, not a helper.

**Comment by olegantonyan** [comment]
Thank you @martndemus  for quick answer!

So, how to add icon after a text? I can wrap the text and icon into different span tags, but this is ugly. Is there another way to do this?

**Comment by martndemus** [comment]
How about just `Login {{fa-icon 'sign-in'}}`? Is that not an option?

**Comment by olegantonyan** [comment]
Probably yes :) Thank you @martndemus
