### ISSUE TITLE
Deprecation Warning in Ember 2.9

### ISSUE THREAD

**Issue by tavosansal** [martndemus/ember-font-awesome#113]
Hello, 
I am getting the following deprecation warning on ```ember serve```: 
```DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super(), addon: `ember-cli-font-awesome` ```

I am wondering if it is enough to change [this line](https://github.com/martndemus/ember-font-awesome/blob/7bf0a36996249794573ec2338f3fcfcef4d5731a/index.js#L11) with: ```this._super(...arguments);``` ? If it is I can create a PR but I am not too familiar with the syntax on that line.

Thank you.

**Comment by leizhao4** [comment]
I had this warning too, but then realized that `ember-cli-font-awesome` has been replaced by `ember-font-awesome` which doesn't have this issue. I upgraded and now the warning is gone. Hope it helps.

**Comment by tavosansal** [comment]
@leizhao4 you are right...this is not an issue
