### ISSUE TITLE
DEPRECATION: Ember CLI addons manage their own module transpilation

### ISSUE THREAD

**Issue by josemarluedke** [martndemus/ember-font-awesome#133]
Getting this deprecation with Ember CLI 2.12.0-beta.2, ember-font-awesome 3.0.4 and ember-cli-babel 5.1.10.

```DEPRECATION: Ember CLI addons manage their own module transpilation during the `treeForAddon` processing. `ember-font-awesome` (found at `/app/node_modules/ember-font-awesome`) has overridden the `this.options.babel` options which conflicts with the addons ability to transpile its `addon/` files properly. Falling back to default babel configuration options.```

**Comment by hoboman313** [comment]
Ember 2.12.0 is out now. I'm seeing this too.

**Comment by rwjblue** [comment]
https://github.com/martndemus/ember-font-awesome/pull/134 should fix

**Comment by sergafts** [comment]
Will there be a new version for this?

**Comment by martndemus** [comment]
3.0.5 published.
