### ISSUE TITLE
Ember Font Awesome needs a new maintainer

### ISSUE THREAD

**Issue by martndemus** [martndemus/ember-font-awesome#136]
I'm looking for someone else to take over maintaining this addon, as I'm not able to put in the time this addon deserves, plus I'm not using the addon in any of the projects I've been on in the past months.

cc @Panman8201

**Comment by buschtoens** [comment]
I'm very much interested in keeping this add-on alive. We rely on it in our company's app.

By the way: Font Awesome promised to offer an official Ember add-on in their Kickstarter campaign. Maybe now's the right time to collaborate with them. 

If not, I'd happily offer a hand or two.

**Comment by martndemus** [comment]
You are now a collaborator on the project!

**Comment by Panman8201** [comment]
I will help when available too (already a Contributor). My ember time is just limited ATM, until next fall.

**Comment by buschtoens** [comment]
@martndemus do you still want to look through all changes and cut new releases? Otherwise feel free to add me as an owner on npm. Same username.

**Comment by bradhaydon** [comment]
@martndemus I would like to help where I can as well, especially with the upcoming FA5 release.

**Comment by martndemus** [comment]
I made @buschtoens and @cibernox maintainers of the repo + gave them rights on npm to publish. I think that should be enough captains on this ship for now.
