### ISSUE TITLE
Manual Usage of FontAwesome 5 with Ember

### ISSUE THREAD

**Issue by MrChriZ** [martndemus/ember-font-awesome#145]
Until ember-font-awesome is updated to work with Ember is there or does anyone have any manual instructions or recommendations as to how to use the FontAwesome5 Alphas with Ember?

Realise this isn't an issue with ember-font-awesome but figure it may be helpful here?
Apologies if not.

**Comment by buschtoens** [comment]
You can [exclude the assets](https://github.com/martndemus/ember-font-awesome#excluding-assets) and then load them yourself. For example via the `vendor` directory.

**Comment by jrjohnson** [comment]
@MrChriZ I got this working today by modifying `ember-cli-build.js` with:

```javascript
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    'ember-font-awesome': {
      includeFontAwesomeAssets: false,
    },
  });

  app.import('vendor/font-awesome-5/fontawesome.js');
  app.import('vendor/font-awesome-5/solid.js');

  return app.toTree();
};
```

and copying assets from the FA5 packages into to `vendor/font-awesome-5`

Hope that helps.

**Comment by jrjohnson** [comment]
@MrChriZ I'm going to close this - please feel free to re-open if your issue wasn't resolved.
