### ISSUE TITLE
4.0.0-alpha.1 too many classes after transform

### ISSUE THREAD

**Issue by jrjohnson** [martndemus/ember-font-awesome#155]
`{{fa-icon icon='adjust'}}`

Should end up as:

`<i aria-hidden="true" class="fa fa-adjust">`

But instead it is transformed into:
`<i aria-hidden="true" class="fa fa-adjust fa-pull- fa-rotate- fa-flip- fa-fw">`

cc/ @cibernox

**Comment by cibernox** [comment]
Released another alpha to fix this.
