### ISSUE TITLE
"times" character not included

### ISSUE THREAD

**Issue by yannski** [martndemus/ember-font-awesome#162]
In my app I use multiple fa-icon helpers with various glyph. They are all visible in dev and they are all visible in production, except when I use the "times" glyph. I tried to rename with "close" but I have the same problem. How can I debug this wrong behavior?

**Comment by cibernox** [comment]
@yannski You mean that `{{fa-icon "times"}}` doesn't work in production?

**Comment by cibernox** [comment]
You're right. I'm checking why.

**Comment by cibernox** [comment]
Ok, I've found why. Fixing it.

**Comment by yannski** [comment]
:+1:

**Comment by cibernox** [comment]
Can you try the next alpha?
