### ISSUE TITLE
Running ember build twice w/o nombom in between causes fa-icons not to render

### ISSUE THREAD

**Issue by snewcomer** [martndemus/ember-font-awesome#164]
We run the below command and then promote `assets`, `fonts`, and the `index.html` to the backend application.  If I run the below command twice subsequently without blowing away and re-installing node modules, fa-icons are loaded; however, the element size is effectively 0x0 pixels.

`./node_modules/ember-cli/bin/ember build --env=production`

tried on both node 7.10 and 8.1.4 with same result.  On ember-font-awesome alpha (4.0.0-alpha.3).  Also tried on alpha.4 with same result

**Comment by snewcomer** [comment]
<img width="112" alt="screen shot 2017-09-15 at 10 23 14 pm" src="https://user-images.githubusercontent.com/7374640/30509397-8f16d3ee-9a64-11e7-95d0-bb15745d5902.png">

vs

<img width="122" alt="screen shot 2017-09-15 at 10 23 58 pm" src="https://user-images.githubusercontent.com/7374640/30509399-9a74b6ca-9a64-11e7-95a0-919cd5184215.png">

**Comment by cibernox** [comment]
Are you on the alpha version?

**Comment by cibernox** [comment]
Nvm, I just read it. I'll try to reproduce it

**Comment by snewcomer** [comment]
Great!  If it is not immediately apparent based on the work you have recently done, I'll do more debugging over the next few days and see if I can get more detail.

**Comment by snewcomer** [comment]
Just to report back - 

1. Tried on v3.0.5 and everything seems to be a-ok.
2. Removed the `PruneUnusedCss` function and same results.
3. Curiously, running the same build command with `ember s` works fine.  However, I believe `ember s` does some further processing on that vendor.css file, so it does include the `fa-**:before` css for some reason.
4.  This PR, although good, didn't help - https://github.com/martndemus/ember-font-awesome/pull/166

@cibernox For the second build, I see that the `fa-**:before` css is gone from the `vendor-**.css` file.

**Comment by snewcomer** [comment]
@jrjohnson yes that is right - it does include `dist tmp`.  Removing those commands sadly doesn't make a difference.  

The caching idea does seem legitimate.  Running `./node_modules/ember-cli/bin/ember build --env=production`, the second time is much faster, but I am not exactly sure what ember-cli is caching.  I did remove the `postprocessTree` command from index, but also got the same results.

The one thing I noticed is that the second run strips out `fa-**:before` css is from the vendor-**.css file.  Still unsure.  Hmmmmm.

**Comment by jrjohnson** [comment]
@snewcomer sorry, I was very unclear. Can you actually *just* do `rm -rf tmp` after your first successfully build. Then do another build and I'm guessing it will work as well. Confirming that the `tmp` directory is the cache source. 

If that doesn't work then try removing `dist` instead and see if you get a second successful build in that case.

This isn't really a solution, but it will clearly point out the problem. If deleting `tmp` between builds fixes the issue then we will need to explore how to bust that cache either through ember-cli or or this addon.

**Comment by snewcomer** [comment]
@cibernox @jrjohnson I'm sorry, I was wrong.  It was the `postprocessTree`.  Confirmed that running build twice with this "properly" removed that the vendor.css is cached and the `fa-**:before` css is still present.

**Comment by snewcomer** [comment]
Just to note, interesting results: 

**`rm -rf tmp dist` or `rm -rf tmp`**

- starting with `vendor-cd**5e.css` - with `fa-**:before` css
1. nombom
2. ember build
-`vendor-cd**5e.css`
3. rm -rf tmp dist or rm -rf tmp
4. ember build
-`vendor-9a**26.css` - no `fa-**:before` css

**Comment by snewcomer** [comment]
And just to clarify more, the only thing that generated a correct `vendor.**.css` file is `rm -rf node_modules && npm install` between builds.

**Comment by cibernox** [comment]
If all goes well, i'll have time tomorrow morning before work to check this.

**Comment by nkgm** [comment]
I'm also experiencing a similar issue in my app when deploying to S3 with `ember-cli-deploy`.

**Comment by cibernox** [comment]
I've found what the issue, but I'm not sure what the right fix would be.
What I believe that happens is that if you build the application, the first time it will traverse the templates and extract the used icons, but if you build it a second time without changing a single comma in your templates, ember-cli detects that the compiled result stored in `/tmp` is still valid and it doesn't run the AST transform again, which means that it doesn't gather the used icons.

If you want to test my theory, build the app twice to generate a bad output, and then change anything on a template (a single letter) and build it again. This time it will be correct again.

I'll ask some wise elder what the right approach would be, but I suspect that I need to persist the used icons into a json file that then I read from the the postcss transform.

**Comment by cibernox** [comment]
@snewcomer can you nombom and install the latest alpha. I believe that this should be fixed, with the exception of deleting templates, but I think that it's acceptable because in the worst case, it might be including a few icons that are not in use anymore after a template was removed, but it won't lack used icons.

**Comment by nkgm** [comment]
Thank you so much @cibernox. This fixes my issue with `ember-cli-deploy`.

**Comment by cibernox** [comment]
@nkgm if you only built the app once you're not really testing that the fix works, as updating dependencies always triggered a rebuild from scratch. You need to build the app the twice without any change in the dependencies to properly test the fix.

Did you try that?

**Comment by nkgm** [comment]
You're right. Deploy for a second time back to back and icons all gone 😞 . Any way I can help with the fix?

**Comment by cibernox** [comment]
I think I've found the cause now. The cache key seems to be different on every execution, defeating the purpose of having a cache at all. Looking into it.

**Comment by nkgm** [comment]
`4.0.0-alpha.10` seems to do the trick 👍

**Comment by snewcomer** [comment]
confirmed.  This works.  Thanks so much!

**Comment by nedcampion** [comment]
Hi All. I'm experiencing this issue and I've only been using `4.0.0-alpha.10`. My travis build runs `ember test` and then does a deploy via `ember-cli-deploy`. When I look at the output `vendor-*.css` I don't see any of the `:before` css. Any help would be much appreciated.
