### ISSUE TITLE
includeStaticIcons option doesn't work

### ISSUE THREAD

**Issue by 0x0badc0de** [martndemus/ember-font-awesome#177]
I have '4.0.0-alpha.10' version installed and it doesn't produce CSS for icons on production (icons are inserted like `{{fa-icon "upload"}}`).
Tried to put icons into `ember-cli-build.js` with no luck:
```
    'ember-font-awesome': {
      includeStaticIcons: ['upload']
    }
```
Seems last one was broken w/ https://github.com/martndemus/ember-font-awesome/pull/172/files#diff-27a70e65b093864d247a2a3a59780200L36 not sure about missing icons at all.

**Comment by ungrim97** [comment]
I am also suffering from both of the above issues.

**Comment by ungrim97** [comment]
Last version I can get to build with icons is 4.0.0-alpha.3

**Comment by cibernox** [comment]
I broke it recently. I'll try to fix it tonight, shouldn't be too hard

**Comment by ungrim97** [comment]
@cibernox Awesome. Thank you

**Comment by cibernox** [comment]
Sorry I couldn't take a look at this yet, I've been travelling. For now the solution can be to stick to 3.X for a little longer, the API is identical, i'll fix this asap

**Comment by cesarizu** [comment]
Is there a way to indicate to include all icons to make it easier to migrate to version 4? Something like `includeStaticIcons: true`?

**Comment by mrukas** [comment]
I can confirm this. Icons are only working if you make development builds. If I downgrade to `4.0.0-alpha.3` icons are also visible in production.

**Comment by cibernox** [comment]
Just giving a heads up that while I dig into this, I created an option to [disable icon removal](https://github.com/martndemus/ember-font-awesome#remove-unused-icons) in production

While we polish this feature better I advice you to disable it. I'll will include all icons regardless of if they are used or not, but it should be temporal while I find the cause.

**Comment by Nippius** [comment]
@cibernox I tried the workaround but the icons still aren't included. I'm using alpha10 with ember 2.16.

This is my code:

```
{{#link-to 'index'}} {{fa-icon "home"}} Home {{/link-to}} 
{{#link-to 'blog'}} {{fa-icon "pencil"}} Blog {{/link-to}} 
{{#link-to 'about'}} {{fa-icon "user-o"}} About {{/link-to}} 
{{#link-to 'projects'}} {{fa-icon "microchip"}} Projects {{/link-to}}
```

**Comment by cibernox** [comment]
Use alpha 11 then.

**Comment by Nippius** [comment]
@cibernox Sorry, I missed that commit. It works fine now, thank you! :)

**Comment by cibernox** [comment]
I believe that this should be fixed in the latest alpha, can anyone confirm.

**Comment by jrjohnson** [comment]
Yes `includeStaticIcons` works in alpha.13.

**Comment by cibernox** [comment]
Good, I now just have to figure out in what circumstances the removal of the unused icons is flacky.
