### ISSUE TITLE
Font-awesome icon disappear in production build

### ISSUE THREAD

**Issue by ankushchaudhary** [martndemus/ember-font-awesome#181]
If I test locally using **ember s** , font awesome icon is working properly, but when i use **ember build --prod** and deployed , **ember-font-awesome** are not showing.

Locally using **ember s** 
<img width="102" alt="screen shot 2017-10-16 at 12 16 15 pm" src="https://user-images.githubusercontent.com/14938108/31598646-60f6a744-b26c-11e7-921f-036cdce02a2a.png">

but in deployed version 
<img width="102" alt="screen shot 2017-10-16 at 12 16 39 pm" src="https://user-images.githubusercontent.com/14938108/31598663-7b641e36-b26c-11e7-962c-ff3c9b2c785b.png">

could you please look into it?

**Comment by cibernox** [comment]
While I find the ultimate cause of this bug, the latest version has an option to [disable icon removal](https://github.com/martndemus/ember-font-awesome#remove-unused-icons)

Set it to false, I'm looking into it. In the meanwhile it would be helpful if you give more information about how you are invoking those icons.

**Comment by ankushchaudhary** [comment]
I am invoking icon like this
**<i class="fa fa-home fa-2x"></i>**
@cibernox

**Comment by cibernox** [comment]
@ankushchaudhary You should use `{{fa-icon "home" size=2}}`

**Comment by ankushchaudhary** [comment]
I tried to use icon , the way you suggest above , but still facing the same issue @cibernox

**Comment by cibernox** [comment]
Did you try disabling icon removal as I commented in the initial response?

**Comment by ankushchaudhary** [comment]
First I put this `'ember-font-awesome': {
    removeUnusedIcons: false // The addon will not remove unused icons, not even in production.
  }` inside **ember-cli-build.js**, then try to use it , but it did not work

**Comment by cibernox** [comment]
@ankushchaudhary Are you on the latest version?

**Comment by ankushchaudhary** [comment]
this is how my dev dependency in package.json is 
` "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "~2.14.2",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.3.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-sass": "^7.0.0",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "~2.14.9",
    "ember-export-application-global": "^2.0.0",
    "ember-font-awesome": "^4.0.0-alpha.10",
    "ember-load-initializers": "^1.0.0",
    "ember-modal-dialog": "^2.3.0",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.14.1",
    "ember-welcome-page": "^3.0.0",
    "loader.js": "^4.2.3"
  }`

**Comment by cibernox** [comment]
Use `4.0.0-alpha.11`

**Comment by ankushchaudhary** [comment]
Thanks @cibernox , now it's working fine .

**Comment by r-darwish** [comment]
I'm using `4.0.0-alpha.13`. No icon will show in production unless I set `removeUnusedIcons: false`. I don't use `<i class="fa">` at all, only `{{fa-icon}}`. In one instance I use an inline if to determine the icon: `{{fa-icon (if lock.exclusive "user" "users")}}`, but even the other icons don't show up.

I'll happily provide more details if necessary, but sadly I can't publish the entire application source.

**Comment by cibernox** [comment]
Yeah, I'm aware that some people is experiencing that but I haven't been able to reproduce it consistently yet. I will try again this week.

**Comment by chewedon** [comment]
I came across this problem today.

Using verison: `"ember-font-awesome": "^4.0.0-alpha.13"`

The way I call it is like so:

```
{{fa-icon "search" class=(if searchText "search-icon-active" "search-icon") click=(action "searchStories")}}
```

My **production Ember application is hosted on Heroku** if that helps with debugging.

The disable icon removal trick fix it for me anyhow.

**Comment by chriswhong** [comment]
Hi all, 
We were experiencing the same issue, `fa-` icons show up in development but not when the app is deployed.  (We are deploying using dokku).  While the app deployed, we saw this error: 

`WARNING: Node v9.2.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.`

By explicitly stating the node version to use in our `package.json`'s `engines` property, (we set it to use 8.9.1, the latest LTS as of today) subsequent deployments worked fine and the icons are visible again,

**Comment by manskx** [comment]
I have seen the same issue today during production deployment. It worked after updating from 4.0.0-alpha.10 to 4.0.0-alpha.11

**Comment by cibernox** [comment]
@manskx If you use the latest version, the problematic functionality (https://github.com/martndemus/ember-font-awesome#remove-unused-icons) is disabled by default. I need to revisit it, but for now wouldn't advice to use it as it might fail on the second deploy.

It does work of on every deploy to clear your `/tmp` folder.

**Comment by manskx** [comment]
@cibernox Thank you !
