### ISSUE TITLE
v4.0.0-rc.1 tag is not published on Github

### ISSUE THREAD

**Issue by bgentry** [martndemus/ember-font-awesome#191]
I'm assuming it's the same commit as what's on Github, but you likely intended to push up the tag as well (that corresponds to the npm release). Cheers :v:

**Comment by buschtoens** [comment]
Whoops. Good catch, thank you. :smile: 

Pushed one now: [v4.0.0-rc.1](https://github.com/martndemus/ember-font-awesome/releases/tag/v4.0.0-rc.1)
