### ISSUE TITLE
Update to newer font-awesome version

### ISSUE THREAD

**Issue by GELight** [martndemus/ember-font-awesome#198]
Hi,

Will you update your ember addon to use the latest font-awesome version?
I use your addon in my projects and it would be very nice to use the latest fa icons. :+1:  :)

Best regards,
Mario

**Comment by jrjohnson** [comment]
@GELight the discussion on updating to Font Awesome 5 is happening at https://github.com/martndemus/ember-font-awesome/issues/143 as well as in the #e-font-awesome channel in the ember community slack workspace.  There is no firm deadline, but those are the places to watch for more information.
