### ISSUE TITLE
Deprecation warning in Ember 3.1

### ISSUE THREAD

**Issue by c410-f3r** [martndemus/ember-font-awesome#206]
Please, update `@ember-decorators/argument` to version `0.8.13` to stop this annoying message:

`DEPRECATION: 'propertyDidChange' is deprecated in favor of 'notifyPropertyChange'`.

I didn't make a PR because I am too dumb to understand why this depencency doesn't have a specified version in `package.json`.

**Comment by buschtoens** [comment]
Closed via #207. Released as `v4.0.0-rc.3`.
