### ISSUE TITLE
fa-icon cannot be used with angle brackets

### ISSUE THREAD

**Issue by HenryVonfire** [martndemus/ember-font-awesome#217]
In a new project with just `ember-font-awesome` installed, using `{{fa-icon "camera"}}` the component works as expected while using `<FaIcon @icon="camera" />` raises the error `Compile Error: Cannot find component fa-icon`

**Comment by jrjohnson** [comment]
This is probably because the build time transform looks for `{{fa-icon}}` specifically. Does enabling the include component option help?

https://github.com/martndemus/ember-font-awesome#add-a-component-for-compatibility

**Comment by HenryVonfire** [comment]
@jrjohnson thanks for the suggestion and your quick response but sadly the error persists

**Comment by wcygan** [comment]
Encountering the same issue... Followed the instructions in the readme:

1. ember install @fortawesome/ember-fontawesome
2. npm i --save-dev @fortawesome/free-solid-svg-icons
3. Add `<FaIcon @icon="coffee" />` in project

Then the compiler barks at you with:

```Compile Error: Cannot find component fa-icon```

**Comment by jrjohnson** [comment]
This is a legacy implementation at this stage, please use https://github.com/FortAwesome/ember-fontawesome for new FA versions as well as new ember features.
