### ISSUE TITLE
Merge error when including ember-font-awesome twice

### ISSUE THREAD

**Issue by carlbennettnz** [martndemus/ember-font-awesome#84]
I have an addon which includes ember-font-awesome in its dependencies and an app which includes both that addon and ember-font-awesome in its devDependencies. I get this error:

```
Merge error: file fonts/FontAwesome.otf exists in /.../tmp/broccoli_merge_trees-input_base_path-673E9WNH.tmp/0 and /.../tmp/broccoli_merge_trees-input_base_path-673E9WNH.tmp/6
```

Is including the same addon twice just something I need to avoid, or is there another problem here?

**Comment by martndemus** [comment]
Yeah, you only need it in one or the other.

**Comment by carlbennettnz** [comment]
I know I only _need_ it once, but if I'm using it in both the addon and the app, doesn't it make sense to include it twice?

**Comment by martndemus** [comment]
If it works, it works, right? ¯\_(ツ)_/¯

**Comment by carlbennettnz** [comment]
Actually, I do need it twice. Even though including it once includes all of the assets, the `{{fa-icon}}` helper is only available when `ember-font-awesome` is in `package.json`

**Comment by aldhsu** [comment]
Had the same problem. Project was including ember-font-awesome in `package.json` and in a custom addon. Reverted to 1.4.2 to as a temporary fix.

**Comment by carlbennettnz** [comment]
@aldhsu 1.4.2 doesn't seem to work for me either. Any idea what it is about that version that made it work for you?

**Comment by aldhsu** [comment]
Didn't look into it because we will eventually remove the dependency in `package.json`. Was a nasty surprise on the integration server that rebuilds frequently (thanks to `package.json` `^`s).

I see from the `1.5.0` change logs `Added a friendly check for the font-awesome bower path`. It might indicate changes to how the the packages are merged now. 

Make sure the `^` is removed from the version in the `package.json`, otherwise it will default to latest. Try `rm -rf node_modules bower_components dist tmp` and then reinstall your dependencies. They will sometimes not rebuild if they already exist.

**Comment by Panman8201** [comment]
@martndemus I have some [logic in another addon that accounts for duplicate importing of the font files](https://github.com/Panman8201/ember-cli-bootswatch/blob/master/index.js#L95-L128). I could make a PR to bring it into this addon if you'd like.

@carlbennettnz I think the "other" addon that has a nested dep for this addon should instead [add a dep to the project](https://github.com/froala/ember-froala-editor/blob/master/blueprints/ember-froala-editor/index.js#L16). What addon is the addon in question?

Also, with the re-name of this addon from `ember-cli-font-awesome` to `ember-font-awesome` make sure you don't a dep for both..

**Comment by martndemus** [comment]
@Panman8201 That would be great!

**Comment by martndemus** [comment]
Can you check out version 2.2.0 and see if that fixes this issue?

**Comment by martndemus** [comment]
This should now be fixed in 3.x, because of the switch to NPM.
