### ISSUE TITLE
Need to install font-awesome thru bower

### ISSUE THREAD

**Issue by greyhwndz** [martndemus/ember-font-awesome#85]
I just installed ember-font-awesome thru `ember install ember-font-awesome` in a new project using `ember-cli 2.4.2`. Got the following error:

`ember-font-awesome: font-awesome is not available from bower (bower_components/font-awesome), install it into your project by running `bower install font-awesome --save` `

Would like to clarify if this is expected.

**Comment by martndemus** [comment]
@Panman8201, you have recently updated `index.js`, could you take a look at this issue?

**Comment by Panman8201** [comment]
@martndemus I just submitted a PR to rename the default blueprint, which was not being run after the addon rename. That's what installs and adds a bower dep for font-awesome.

@greyhwndz In the mean time, the solution is to run the command that the error message gives you; `bower install font-awesome --save`

**Comment by greyhwndz** [comment]
@Panman8201 Yea I did tried the command in the meantime. Thanks
