### ISSUE TITLE
Deprecation warning: Addon: `ember-cli-font-awesome` is missing addon.project

### ISSUE THREAD

**Issue by edslocombe** [martndemus/ember-font-awesome#97]
I've created an addon (private) and included ember-cli-font-awesome. As soon as this dependency is added the build outputs the following deprecation warning:

```
DEPRECATION: Addon: `ember-cli-font-awesome` is missing addon.project, this may be the result of an addon forgetting to invoke `super` in its init.
DEPRECATION: Addon: `ember-computed-decorators` is missing addon.project, this may be the result of an addon forgetting to invoke `super` in its init.
DEPRECATION: Addon: `ember-cli-font-awesome` is missing addon.project, this may be the result of an addon forgetting to invoke `super` in its init.
```

I have little experience creating addons so apologies if this is as a result of my setup, but maybe someone could shed some light on this..?

- ember-cli: 2.6.1
- node: 4.2.6

Thanks.

**Comment by martndemus** [comment]
This is already fixed in the latest version of `ember-font-awesome`. If you care about the message going away you should upgrade it.

**Comment by edslocombe** [comment]
Perfect, confused but all good. I had tried to update to the latest but had used:

`ember install ember-cli-font-awesome`

Dropping the `cli` and uninstalling that does the the job!

Thanks!

**Comment by martndemus** [comment]
@edslocombe did you install `ember-cli-font-awesome`  via a tutorial or guide? If so, could you share which guide, I'd like to reach out to fix the install.

**Comment by edslocombe** [comment]
It was from Google, searched for _ember-cli-font-awesome_ and the NPM page is obviously the first hit:

https://www.npmjs.com/package/ember-cli-font-awesome
