### ISSUE TITLE
helper not found

### ISSUE THREAD

**Issue by dfalling** [martndemus/ember-font-awesome#99]
I'm trying to migrate over from ember-cli-font-awesome to ember-font-awesome, but I can't get the helper to show up.  I'm getting `Error: Assertion Failed: A helper named 'fa-icon' could not be found` in an integration test, and `TypeError: Attempting to register an unknown factory: helper:fa-icon` in my unit tests.  I used `ember install ember-font-awesome` and `ember generate ember-font-awesome` and cleaned node_modules and bower_components for good measures.  Is there something else I need to do to migrate over?  Thanks!

**Comment by BryanH** [comment]
Try this:

- `npm i`
- `bower i`

You may need to restart your server.

**Comment by dfalling** [comment]
Sorry, I should have mentioned I already did that.  I went as far as flushing everything out with no luck:
`npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install`

**Comment by Kuzirashi** [comment]
Same for me. Test suite for this addon fails. How is this possible someone accepted pull request that breaks addon having test suite indicating half of the test is failing? :P

**Comment by martndemus** [comment]
I fixed the test suite and released a new version, did that fix your problem?

**Comment by paulbhartzog** [comment]
still broke :-(

**Comment by brettchalupa** [comment]
I just ran into this problem as part migrating like @dfalling, and I don't believe this is an issue with this add-on but is with the tests.

`{{fa-icon}}` in `ember-font-awesome` now comes from a component, not a helper. This means in the `needs: []` of unit tests, use `'component:fa-icon'` instead of `'helper:fa-icon'` (which was what was used in `ember-cli-font-awesome`).

A find and replace of `'helper:fa-icon'` with `'component:fa-icon'` should fix the issue.

For example:

``` js
import {
  moduleForComponent,
  test
} from 'ember-qunit';

moduleForComponent('foo', {
  needs: [
    'component:fa-icon'
  ]
});

test('it renders', function(assert) {
  assert.expect(2);

  // Creates the component instance
  var component = this.subject();
  assert.equal(component._state, 'preRender');

  // Renders the component to the page
  this.render();
  assert.equal(component._state, 'inDOM');
});
```

**Comment by dfalling** [comment]
I'm not working on that project any more, but I'm confident @brettchalupa nailed it on the head.  Good catch.  If someone else can confirm this I'll close out this ticket.

**Comment by martndemus** [comment]
Yes, that could be it.
